export const BATCH_OPTION = [
  '2022',
  '2021',
  '2020',
  '2019',
  '2018',
  '2017',
  'Alumni',
];

export const DEPARTMENT_OPTION = [
  'Actuarial Science',
  'Architecture',
  'Automation Electronic Engineering',
  'Biology',
  'Biomedical Engineering',
  'Business Management',
  'Business Statistics',
  'Chemical Engineering',
  'Chemistry',
  'Civil Engineering',
  'Civil Infrastructure Engineering',
  'Computer Engineering',
  'Developmental Studies',
  'Electrical Engineering',
  'Environmental Engineering',
  'Geomatics Engineering',
  'Geophysics Engineering',
  'Industrial Chemical Engineering',
  'Industrial Mechanical Engineering',
  'Industrial Product Design',
  'Informatics',
  'Information Systems',
  'Information Technology',
  'Instrumentation Engineering',
  'Interior Design',
  'Marine Engineering',
  'Material Engineering',
  'Mathematics',
  'Mechanical Engineering',
  'Naval Architecture and Shipbuilding Engineering',
  'Ocean Engineering',
  'Physics',
  'Physics Engineering',
  'Regional and Urban Planning',
  'Sea Transportation Engineering',
  'Statistics',
  'Systems and Industrial Engineering',
  'Technology Management',
  'Visual Communication Design',
];
